hello-kubernetes quickstart should show how to curl the running app
dapr/quickstarts pull request #371
Opened 2021-01-17 05:52 UTC by yoDon

# Description

Adds example of how to curl into a dapr app that is running under kubernetes

## Issue reference

This PR will close https://github.com/dapr/quickstarts/issues/370

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] The quickstart code compiles correctly
* [X] You've tested new builds of the quickstart if you changed quickstart code
* [X] You've updated the quickstart's README if necessary

2021-02-02 05:05 UTC, wcs1only requested changes
Our quickstarts are now self validating. You can annotate your change in the markdown file to have it be executed automatically and have its output automatically validated. This helps us make sure our documents are working correctly with every release.

See: https://github.com/dapr/quickstarts/blame/master/hello-kubernetes/README.md#L129-L141 for an example. For the complete documentation of our validation framework, and the checks that it supports, see: https://github.com/dapr/mechanical-markdown/tree/main/examples

If you don't have the time or inclination to give this a shot, let me know and I'll create a separate issue to add validation to these steps.

2021-02-14 23:27 UTC, yoDon commented on hello-kubernetes/README.md
> +curl --request POST --data "{\"data\": { \"orderId\": \"42\" } }" --header "Content-Type:application/json" http://localhost/neworder
I've applied the changes you suggested (localhost -> $NODE_APP) and added automated tests for the curl examples I added.

2021-02-22 02:23 UTC, yoDon commented on hello-kubernetes/README.md
> +curl http://localhost/order
I've applied the changes you suggested (localhost -> $NODE_APP) and added automated tests for the curl examples I added.

2021-02-22 02:27 UTC, yoDon reviewed
@wcs1only I've applied your changes and the PR is ready to review (github is still reporting them as unresolved, but it wont let me apply your changes as I've already applied them myself)

2021-03-05 21:08 UTC, wcs1only commented on hello-kubernetes/README.md
> +curl http://localhost/order
Awesome, thanks!

2021-03-05 21:26 UTC, wcs1only commented on hello-kubernetes/README.md
> +
```suggestion
<!-- END_STEP -->

```

The missing END_STEP tag was making our autovalidation skip this step. Our parser *should* have thrown an error for this case, which means we probably have an error in our markdown automation tool: https://github.com/dapr/mechanical-markdown . I'll go ahead and fix this so we can get your PR merged, but I'll see if I can make a test for this in the upstream tool.

2021-03-05 21:48 UTC, wcs1only commented on hello-kubernetes/README.md
> +
I've created an issue to track the bug you exposed: https://github.com/dapr/mechanical-markdown/issues/8

Thanks!

2021-03-05 21:48 UTC, wcs1only approved these changes

2021-03-05 21:51 UTC, merged