hello-world - add folder paths to launch for split projects
dapr/quickstarts pull request #493
Opened 2021-11-14 00:29 UTC by tonysurma

# Description

In the hello-world quickstart, I added folder paths to launch.json for split projects.  The combination of adding in the split project folders for node and python as well as the addition of the VS Code debugging configurations are out of synch and corrected by adding the additional folder paths in launch.json for the hello-world quickstart.

## Issue reference

closes #492 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [X] The quickstart code compiles correctly
* [X] You've tested new builds of the quickstart if you changed quickstart code
* [X] You've updated the quickstart's README if necessary

2021-11-17 19:16 UTC, wcs1only submitted a review, later dismissed

2022-02-15 16:50 UTC, greenie-msft submitted a review, later dismissed

2022-02-25 05:42 UTC, paulyuk commented
Hi @tonysurma, I unblocked the tests so they can run.  Could you please ensure they pass, and also click on the DCO workflow step above and sign the DCO?  you can alternatively use a `git commit -s -p` in the future to sign your commit and see the changes before pushing.

2022-02-25 05:43 UTC, paulyuk commented
BTW nice catch and thank you much for the contribution

2022-02-25 06:17 UTC, paulyuk commented
Hi Tony, i see the tests failed based on a test bug we fixed in `master` branch.  Please sync your branch and fork with remote master, merge and push.  You'll get updated readme.md files with fixed tests, and all should work dandy after that. 

Here is the test bug that got fixed: https://github.com/dapr/quickstarts/pull/548

2022-02-25 19:35 UTC, tonysurma commented
thank you both, will do that soon and glad this contribution can make it in

2022-02-26 19:58 UTC, paulyuk requested changes
Just flipping to request changes until you can merge the test fix and resubmit. this way I know we're waiting on something.

2022-03-02 00:16 UTC, tonysurma commented
rebased with DCO so should be good to go - thanks again

2022-03-03 00:03 UTC, tonysurma commented
rebased again and requested review, thanks again

2022-04-26 22:36 UTC, yaron2 commented
@tonysurma apologies it has taken so long to merge. please resolve the conflicts one last time and we'll merge :)

2022-04-27 06:15 UTC, amulyavarote commented
Do we still need this based on our new quickstarts structure?

2022-04-27 20:17 UTC, amulyavarote commented
@tonysurma Can you please take the recent changes from master and rebase this with master and push the changes?

2022-04-27 20:29 UTC, tonysurma commented
Yes, will do as soon as I can

2022-05-01 18:48 UTC, tonysurma commented
before I do I wanted to verify the following approach given the changes.  I see that hello-world has moved under tutorials so will do the update there.  However I also see that the whole .vscode directory that was under the hello-world tutorial is now removed.  To reapply this change I would need to recreate the .vscode directory and the two files that were there prior and add this path update.

Do you agree with this approach?  Thanks.

2022-05-02 03:49 UTC, amulyavarote commented
> before I do I wanted to verify the following approach given the changes. I see that hello-world has moved under tutorials so will do the update there. However I also see that the whole .vscode directory that was under the hello-world tutorial is now removed. To reapply this change I would need to recreate the .vscode directory and the two files that were there prior and add this path update.
> 
> Do you agree with this approach? Thanks.

Hi! Yea It looks good to me. Please push the changes to the PR. We will talk a look.

2022-05-17 17:46 UTC, amulyavarote commented
@tonysurma Do you have any updates on this PR?

2022-05-21 01:22 UTC, msfussell commented
@tonysurma - Ping?

2022-05-21 03:12 UTC, tonysurma commented
apologies @msfussell and @amulyavarote for delay.  I realized I had to recreate the whole branch to 'move' over to the new structure etc. and wanted to do it in this PR branch.  Some git commands later and should be good to go.

2022-05-23 19:21 UTC, amulyavarote commented
@tonysurma Can you please rebase the changes with master and push the changes?

2022-05-23 19:44 UTC, tonysurma commented
Done, thx

2022-05-23 22:05 UTC, msfussell approved these changes
LGTM

2022-05-23 22:05 UTC, merged