Quickstart example for State Management in Java
dapr/quickstarts pull request #535
Opened 2022-02-16 12:19 UTC by pravinpushkar

Signed-off-by: Pravin Pushkar <ppushkar@microsoft.com>

# Description

Quickstart example for State Management in Java

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: NA

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-02-17 09:27 UTC, paulyuk requested changes
Please sync up with Amulya's changes from While w/ random to For i.  Enables testing.

2022-02-17 09:27 UTC, paulyuk commented on state_management/java/http/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
> +            Random random = new Random();
Please see @amulyavarote's latest PR on changing random to well known for loop.  She decided random is going to block testability, and I agree.

As a part of change please check you've removed unused imports for java.util.Random

2022-02-17 09:27 UTC, paulyuk commented on state_management/java/sdk/order-processor/src/main/java/com/service/OrderProcessingServiceApplication.java
> +                Random random = new Random();
Another please convert while loop with random to for loop on i.

2022-02-21 05:01 UTC, pravinpushkar commented
> Please sync up with Amulya's changes from While w/ random to For i. Enables testing.

Done in latest commit.

2022-02-23 05:30 UTC, artursouza approved these changes

2022-02-23 05:30 UTC, merged