Added service invocation examples
dapr/quickstarts pull request #536
Opened 2022-02-16 23:48 UTC by amulyavarote

Signed-off-by: Amulya Varote <amulyavarote@QTM-SWATHIKIL-1.redmond.corp.microsoft.com>

# Description

Added service invocation examples for dotnet, go, javascript and python

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: NA

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] The quickstart code compiles correctly
* [ ] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-02-17 08:07 UTC, pravinpushkar commented
I think README.md files need to be adjusted according to suggestion given by @paulyuk

2022-02-17 09:20 UTC, paulyuk requested changes
Just a few things. 

Also in the /go/* folders there are two binary files called app.  Should we gitignore these?

2022-02-17 09:20 UTC, paulyuk commented on service_invocation/csharp/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. See [Why Service-Invocation](#why-service-invocation)
```suggestion
In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. 
```
The why service invocation content does not exist so lets remove this.

2022-02-17 09:20 UTC, paulyuk commented on service_invocation/csharp/http/checkout/Program.cs
> +    client.DefaultRequestHeaders.Add("dapr-app-id", "order-processor");
Since the client is scoped at the class level, let's just do this once and move below line 8.

2022-02-17 09:20 UTC, paulyuk commented on service_invocation/go/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. See [Why Service-Invocation](#why-service-invocation)
```suggestion
In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. 
```

2022-02-17 09:20 UTC, paulyuk commented on service_invocation/javascript/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. See [Why Service-Invocation](#why-service-invocation)
```suggestion
In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. 
```

2022-02-17 09:20 UTC, paulyuk commented on service_invocation/python/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. See [Why Service-Invocation](#why-service-invocation)
```suggestion
In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. 
```

2022-02-17 09:20 UTC, paulyuk commented on service_invocation/python/http/checkout/app.py
> +import random
We can delete

2022-02-24 18:36 UTC, paulyuk requested changes
Just a few minor items left

2022-02-24 18:36 UTC, paulyuk commented on service_invocation/javascript/http/checkout/package.json
> +        "axios": "^0.25.0"
```suggestion
        "axios": "^0.26.0"
```

2022-02-24 18:36 UTC, paulyuk commented on service_invocation/python/http/checkout/app.py
> +    headers = {'dapr-app-id': 'order-processor'}
please move out of loop, maybe line 11?

2022-02-24 18:36 UTC, paulyuk commented on service_invocation/python/http/checkout/app.py
> +    # Adding app id as part of th header
```suggestion
    # Adding app id as part of the header
```

2022-02-24 18:51 UTC, greenie-msft commented on service_invocation/javascript/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern.
Consider being a little more descriptive with the example. 

"The checkout service will use Dapr's http proxying capability to invoke a method in the order processing service." or something along those lines.

2022-02-24 18:52 UTC, greenie-msft commented on service_invocation/javascript/http/checkout/index.js
> +    // Adding app id as part of th header
```suggestion
    // Adding app id as part of the header
```

2022-02-25 05:40 UTC, paulyuk approved these changes
Amazing feature add, thank you.

LGTM

2022-02-27 20:58 UTC, msfussell commented on service_invocation/csharp/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. The checkout service will use Dapr's http proxying cap
```suggestion
In this quickstart, you'll create a checkout service and an order processor service to demonstrate how to use the service invocation API. The checkout service uses Dapr's http proxying capability to invoke a method in the order processing service.
```

2022-02-27 20:59 UTC, msfussell commented on service_invocation/csharp/http/README.md
> +# Dapr Service Invocation
```suggestion
# Service Invocation
```

2022-02-27 20:59 UTC, msfussell commented on service_invocation/csharp/http/README.md
> +Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and Service Invocation.
```suggestion
Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and service invocation.
```

2022-02-27 20:59 UTC, msfussell commented on service_invocation/csharp/http/README.md
> +And one order-processor service:
```suggestion
And one order processor service: 
```

2022-02-27 21:00 UTC, msfussell commented on service_invocation/csharp/http/README.md
> +1. Open a new terminal window and navigate to `checkout` directory:
```suggestion
1. Open a new terminal window and navigate to the `checkout` directory: 
```

2022-02-27 21:02 UTC, msfussell commented on service_invocation/go/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. The checkout service will use Dapr's http proxying cap
```suggestion
In this quickstart, you'll create a checkout service and an order processor service to demonstrate how to use the service invocation API. The checkout service uses Dapr's http proxying capability to invoke a method on the order processing service.
```

2022-02-27 21:02 UTC, msfussell commented on service_invocation/go/http/README.md
> +Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and Service Invocation.
```suggestion
Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and service invocation.
```

2022-02-27 21:03 UTC, msfussell commented on service_invocation/go/http/README.md
> +And one order-processor service:
```suggestion
And one order processor service: 
```

2022-02-27 21:04 UTC, msfussell commented on service_invocation/go/http/README.md
> +# Dapr Service Invocation
```suggestion
# Service Invocation
```

2022-02-27 21:04 UTC, msfussell commented on service_invocation/javascript/http/README.md
> +# Dapr Service Invocation
```suggestion
# Service Invocation
```

2022-02-27 21:04 UTC, msfussell commented on service_invocation/javascript/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. The checkout service will use Dapr's http proxying cap
```suggestion
In this quickstart, you'll create a checkout service and an order processor service to demonstrate how to use the service invocation API. The checkout service uses Dapr's http proxying capability to invoke a method on the order processing service.
```

2022-02-27 21:05 UTC, msfussell commented on service_invocation/javascript/http/README.md
> +Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and Service Invocation.
```suggestion
Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and service invocation.
```

2022-02-27 21:05 UTC, msfussell commented on service_invocation/python/http/README.md
> +# Dapr Service Invocation
```suggestion
# Service Invocation
```

2022-02-27 21:05 UTC, msfussell commented on service_invocation/python/http/README.md
> +In this quickstart, you'll create a checkout service and a order processor service to demonstrate how Dapr enables a service invocation pattern. The checkout service will use Dapr's http proxying cap
```suggestion
In this quickstart, you'll create a checkout service and an order processor service to demonstrate how to use the service invocation API. The checkout service uses Dapr's http proxying capability to invoke a method on the order processing service.
```

2022-02-27 21:06 UTC, msfussell commented on service_invocation/python/http/README.md
> +Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and Service Invocation.
```suggestion
Visit [this](https://docs.dapr.io/developing-applications/building-blocks/service-invocation/) link for more information about Dapr and service invocation.
```

2022-02-27 21:06 UTC, msfussell commented on service_invocation/python/http/README.md
> +And one order-processor service:
```suggestion
And one order processor service: 
```

2022-02-28 21:41 UTC, msfussell commented
@amulyavarote - Do you want to take a look at the failure above?

2022-02-28 21:43 UTC, amulyavarote commented
> @amulyavarote - Do you want to take a look at the failure above?

yes. The PR builds are failing. We are looking into it

2022-03-01 18:38 UTC, tanvigour commented
#557

2022-03-04 00:02 UTC, paulyuk approved these changes
Thank you @amulyavarote !  LGTM

2022-03-04 00:03 UTC, paulyuk commented
The tests failures are flakiness on mac caused by some latencies and the same docker rate limiting we know about (fix in hand)

2022-03-04 00:32 UTC, merged

2024-07-24 04:53 UTC, joebowbeer commented
One timing problem that occurred when I ran the javascript/http example in the devcontainer:

The order-processor may not be ready to receive the first order from the checkout service, in which case the first post returns a 500 and exits the checkout loop.

Moving the sleep to the top of the loop helps.

I think this problem and potential improvement applies to all of these service_invocation implementations.

Is there a better way for checkout to wait until the order-processor is running?

2024-10-25 11:07 UTC, RGraham1931 approved these changes