Testing GitHub actions for new quickstarts directory structure
dapr/quickstarts pull request #538
Opened 2022-02-17 19:50 UTC by amulyavarote

# Description

Testing github actions

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: NA

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] The quickstart code compiles correctly
* [ ] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-02-18 21:47 UTC, artursouza requested changes

2022-02-18 21:47 UTC, artursouza commented on .github/workflows/build.yml
> -      - master
Please, keep master too.

2022-02-18 21:47 UTC, artursouza commented on .github/workflows/build.yml
> +      - feature/new_quickstarts
Please, keep master too.

2022-02-18 21:47 UTC, artursouza commented on .github/workflows/validate.yaml
>  on:
Same feedback for this workflow.

2022-02-18 21:47 UTC, artursouza commented on tutorials/observability/README.md
> +For this quickstart, a configuration has already been enabled for every service in the distributed calculator app. You can find the annotation in each one of the calculator yaml files. For example re
Keep this in master since we will not keep the new_quickstarts branch forever.

2022-02-18 21:47 UTC, artursouza commented on tutorials/observability/README.md
> +If this is the first time trying the distributed calculator, find more detailed instructions in the [distributed-calculator](https://github.com/dapr/quickstarts/tree/feature/new_quickstarts/tutorials
keep master

2022-02-19 00:36 UTC, paulyuk approved these changes
lgtm pending Artur's changes

2022-02-19 00:38 UTC, paulyuk reviewed
Let's get Arturs suggestion in since this branch will go away later.

2022-02-19 03:28 UTC, paulyuk commented
@artursouza  lgtm now.  you?

2022-02-22 18:49 UTC, artursouza approved these changes

2022-02-22 18:49 UTC, merged