Add test triggers for all new tests in validate
dapr/quickstarts pull request #592
Opened 2022-03-10 19:32 UTC by tanvigour

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #551 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] The quickstart code compiles correctly
* [ ] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-03-14 23:47 UTC, artursouza approved these changes

2022-03-14 23:48 UTC, artursouza requested changes
There seems to be an issue with path to components folder.

2022-03-16 14:33 UTC, tanvigour commented
@artursouza  sorry didn't mean to re-request the review. the change is still in progress

2022-03-16 16:49 UTC, tanvigour commented
creating a new PR for new separate validators , closing this one

2022-03-16 16:49 UTC, closed without merging