Put reader in 'node' dir
dapr/quickstarts pull request #595
Opened 2022-03-11 15:46 UTC by duglin

W/o this change the reader might not realize they need to cd into the
'node' dir to see the app.js file that we talk about next.

Also removed some extra whitespace at the end of some lines.

Wasn't sure which branch to base this off of, let me know if you want it moved.

Signed-off-by: Doug Davis <dug@microsoft.com>

2022-03-16 06:18 UTC, paulyuk requested changes
Thanks Doug for the contributions and nice catch - Step 2 did not sync with the ./node changes in Step 3.  One small thing to tweak for consistency, and then LGTM.

2022-03-16 06:18 UTC, paulyuk commented on hello-world/README.md
> +Now that Dapr is set up locally, clone the repo, then navigate to the node version of the Hello World quickstart:
```suggestion
Now that Dapr is set up locally, clone the repo, then navigate to the Node.js version of the Hello World quickstart:
```

2022-03-16 06:26 UTC, paulyuk commented on hello-world/README.md
> +Now that Dapr is set up locally, clone the repo, then navigate to the node version of the Hello World quickstart:
Oh for @greenie-msft, should this get pushed to the feature_newquickstarts branch, /tutorials/.. folder too?

2022-03-16 14:14 UTC, paulyuk submitted a review, later dismissed
Lgtm

2022-03-22 19:37 UTC, duglin commented
rebased - should be good to go now.

2022-03-24 00:29 UTC, paulyuk approved these changes

2022-03-24 00:41 UTC, merged