Final change to migrate Bindings test to GHCR (action now in dapr/dapr)
dapr/quickstarts pull request #603
Opened 2022-03-15 19:56 UTC by paulyuk

Signed-off-by: Paul Yuknewicz <paulyuk@microsoft.com>

This ensures our flaky binding tests pull via docker compose from GHCR registry.  

## Issue reference

[Request: run docker-mirror-container action and set permissions · Issue #4377 · dapr/dapr (github.com)](https://github.com/dapr/dapr/issues/4377)

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [x] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-03-15 19:57 UTC, tanvigour submitted a review, later dismissed
LGTM. Thanks Paul!

2022-03-16 01:24 UTC, msfussell approved these changes

2022-03-16 01:25 UTC, msfussell approved these changes

2022-03-16 02:57 UTC, artursouza requested changes

2022-03-16 02:57 UTC, artursouza commented on bindings/docker-compose-single-kafka.yml
> +    image: ghcr.io/dapr/3rdparty/kakfa:latest
typo.

2022-03-16 04:07 UTC, artursouza approved these changes

2022-03-16 05:04 UTC, merged