Add back PR trigger
dapr/quickstarts pull request #605
Opened 2022-03-16 17:01 UTC by tanvigour

Signed-off-by: tanvigour <tanvi.gour@gmail.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #568

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] The quickstart code compiles correctly
* [ ] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-03-16 17:22 UTC, artursouza requested changes

2022-03-16 17:22 UTC, artursouza commented on .github/workflows/build.yml
> +        if: github.event_name != 'pull_request'
What is the purpose of this workflow to be triggered in PRs if we exclude the build step from it?

2022-03-16 22:15 UTC, paulyuk approved these changes
LGTM

2022-03-17 01:02 UTC, artursouza approved these changes

2022-03-17 01:02 UTC, merged