Initial commit for Bindings Quickstart for Javascript, go, Python and…
dapr/quickstarts pull request #648
Opened 2022-04-14 16:50 UTC by nirmash

… C# (http and SDK)

Signed-off-by: Nir Mashkowski <nimashkowski@microsoft.com>

# Description

Created a Quickstart for Bindings to add to Dapr.io docs

## Issue reference

n/a

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] The quickstart code compiles correctly
* [x] You've tested new builds of the quickstart if you changed quickstart code
* [x] You've updated the quickstart's README if necessary
* [no will need help creating a test for this Quickstart ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-04-14 18:14 UTC, amulyavarote commented on bindings/csharp/http/input/input.cs
> +app.MapPost("/sample-topic", (Order requestData) => {
Can we keep it as "/orders" (like we have in pubsub examples)?

2022-04-14 18:15 UTC, amulyavarote commented on bindings/csharp/sdk/output/output.cs
> +var bindingName = "sample-topic";
Can we keep it as "orders"? Sample-Topic is very generic

2022-04-14 18:16 UTC, amulyavarote commented on bindings/go/http/input.go
> +	bindingName := "/sample-topic"
Same as above

2022-04-14 18:16 UTC, amulyavarote commented on bindings/go/http/output.go
> +	bindingName := "sample-topic"
Same as above

2022-04-14 18:16 UTC, amulyavarote commented on bindings/go/sdk/input.go
> +	bindingName := "/sample-topic"
same as above

2022-04-14 18:17 UTC, amulyavarote commented on bindings/go/sdk/output.go
> +	bindingName := "sample-topic"
Can we keep it as "orders" sample-topic is very generic?

2022-04-14 18:18 UTC, amulyavarote commented on bindings/javascript/http/output.js
> +const KAFKA_TOPIC = process.env.DAPR_KAFKA_TOPIC || "sample-topic";
Lets try to keep the variable names consistent across all the programming languages. (Keep one: kafka_topic or binding_topic). And also keep it as "orders"

2022-04-14 18:18 UTC, amulyavarote commented on bindings/javascript/sdk/input.js
> +  const bindingName = "sample-topic";
Same as above

2022-04-14 18:19 UTC, amulyavarote commented on bindings/python/http/input.py
> +@app.route('/sample-topic', methods=['POST'])
Same as above!

2022-04-14 18:19 UTC, amulyavarote commented on bindings/python/http/output.py
> +binding_name = "sample-topic"
Same as above. Lets keep it as "orders"

2022-04-14 18:19 UTC, amulyavarote commented on bindings/python/sdk/input.py
> +bindingName = "sample-topic"
Same as above

2022-04-14 18:20 UTC, amulyavarote commented on bindings/python/sdk/output.py
> +    bindingName = "sample-topic"
Same as above

2022-04-14 18:21 UTC, amulyavarote commented
lets try to keep the variable names, method names and print statements consistent across all the languages.

2022-04-14 18:23 UTC, amulyavarote commented on bindings/python/sdk/output.py
> +        print ('Python - Kafka SDK output binding: orderId: ' + str(n),flush=True)
Lets keep the print statements same across

2022-04-14 18:24 UTC, amulyavarote commented on bindings/python/http/input.py
> +    logger.info('Python - Kafka HTTP input binding: ' + event_orderid)
No need to have the language specified in the print statements.

2022-04-14 18:24 UTC, amulyavarote commented on bindings/javascript/sdk/output.js
> +    console.log("Javascript - Kafka SDK output binding: " + JSON.stringify(order));
No need to have the language specified in the print statements.

2022-04-14 18:24 UTC, amulyavarote commented on bindings/javascript/sdk/input.js
> +  const response = await server.binding.receive(bindingName, async (data) => console.log(`Javascript - Kafka SDK input binding: ${JSON.stringify(data)}`));
No need to have the language specified in the print statements.

2022-04-14 18:24 UTC, amulyavarote commented on bindings/javascript/http/output.js
> +        console.log("Javascript - Kafka HTTP output binding: " + response.config.data);
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/javascript/http/input.js
> +    console.log("Javascript - Kafka HTTP input binding: " + JSON.stringify(req.body));
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/go/sdk/output.go
> +		fmt.Println("Golang - Kafka SDK output binding: ", order)
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/go/sdk/input.go
> +	fmt.Println("Golang - Kafka SDK input binding: ", string(in.Data))
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/go/http/output.go
> +		fmt.Println("Golang - Kafka HTTP output binding: ", order)
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/go/http/input.go
> +	fmt.Println("Golang - Kafka HTTP input binding: ", string(data))
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/csharp/sdk/output/output.cs
> +    Console.WriteLine("C# - Kafka SDK output binding: " + order);
No need to have the language specified in the print statements.

2022-04-14 18:25 UTC, amulyavarote commented on bindings/csharp/http/output/output.cs
> +    Console.WriteLine("C# - Kafka HTTP output binding: " + orderJson);
No need to have the language specified in the print statements.

2022-04-14 18:26 UTC, amulyavarote commented on bindings/csharp/http/input/input.cs
> +    Console.WriteLine("C# - Kafka HTTP input binding: { \"orderId\": " + requestData.OrderId + "}");
No need to have the language specified in the print statements.

2022-04-14 18:27 UTC, amulyavarote requested changes
Please make the changes to the print statements, variable names, method names and binding topic.

2022-04-28 22:31 UTC, amulyavarote commented
@nirmash Can you rebase this PR with master and push the changes for the builds to be successful?

2022-04-28 22:52 UTC, nirmash commented
I am in the process of rewriting the Quickstart, will take a bit of time and I will rebase and resubmit. I am not that experienced with pull requests but perhaps we can just close \ cancel this one?

2022-05-05 22:15 UTC, closed without merging