701: Java quickstarts cleanup:
dapr/quickstarts pull request #702
Opened 2022-07-08 11:44 UTC by bibryam

Signed-off-by: Bilgin Ibryam <bibryam@gmail.com>

# Description

- Removed unused imports
- Code style: add space after statements
- Removed unused test code
- Moved Dapr client creation outside of loops
- Update dapr-sdk versions to 1.5
- Added Maven artifact name and description where missing
- Aligned Maven artifact names to camel case

## Issue reference

https://github.com/dapr/quickstarts/issues/701

Please reference the issue this PR will close: #_[701]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x ] The quickstart code compiles correctly
* [ x] You've tested new builds of the quickstart if you changed quickstart code
* [ x] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-07-10 21:12 UTC, bibryam commented
These code changes also require changes in the docs. The corresponding PR in the docs is here docs/pull/2639

2022-07-11 16:41 UTC, paulyuk requested changes
Thank you much @bibryam -- this brings good idiomatic changes for Java.  There's just one minor change suggested and then I'll take it.

2022-07-11 16:41 UTC, paulyuk commented on bindings/java/http/batch/src/main/java/com/service/controller/BatchProcessingServiceController.java
> +        try (InputStream is = getClass().getClassLoader().getResourceAsStream(path)) {
removing mock is ok.  I agree with this.

2022-07-11 16:41 UTC, paulyuk commented on pub_sub/java/sdk/checkout/src/main/java/com/service/CheckoutServiceApplication.java
> +		DaprClient client = new DaprClientBuilder().build();
good catch.  thank you.

2022-07-12 20:37 UTC, bibryam commented on bindings/java/http/batch/pom.xml
> +	<description>Quickstart for Dapr Bingings building block</description>
thanks, this is fixed now. Notice also the related quickstart docs PR in the docs project :)

2022-07-12 22:22 UTC, paulyuk approved these changes
LGTM.  thank you for this @bibryam !

2022-07-12 22:44 UTC, merged