Added parallelism to pubsub workflow
dapr/quickstarts pull request #729
Opened 2022-08-24 17:52 UTC by amulyavarote

Signed-off-by: Amulya Varote <amulyavarote@microsoft.com>

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] The quickstart code compiles correctly
* [ ] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2022-08-27 17:53 UTC, paulyuk requested changes
Looks like a good overall improvement for perf and throughput of testing.

Have we validated that no state is shared (e.g. ports etc) that will cause collisions during parallel tests?

What about C# support?

2022-08-27 17:53 UTC, paulyuk commented on .github/workflows/validate_new_quickstarts_pubsub.yaml
> +        quickstart_language: [go, javascript, python, java]
csharp?

2022-08-27 17:53 UTC, paulyuk commented on .github/workflows/validate_new_quickstarts_secrets_management.yaml
> +        quickstart_language: [go, javascript, python, java]
csharp?

2022-08-27 17:53 UTC, paulyuk commented on .github/workflows/validate_new_quickstarts_service_invo.yaml
> +        quickstart_language: [go, javascript, python, java]
csharp?

2022-08-27 17:53 UTC, paulyuk commented on .github/workflows/validate_new_quickstarts_state_management.yaml
> +        quickstart_language: [go, javascript, python, java]
csharp?

2022-08-29 21:04 UTC, amulyavarote commented
@paulyuk There are separate flows for all the building blocks. And in each building block(in each workflow), the ports are different for different examples. So I think there should not be any conflict in the resources.

2022-08-29 23:53 UTC, amulyavarote commented
> Looks like a good overall improvement for perf and throughput of testing.
> 
> Have we validated that no state is shared (e.g. ports etc) that will cause collisions during parallel tests?
> 
> What about C# support?

As we have different workflow for each building block. I think there is no sharing of resources. And examples use  different port numbers under each building block.

2022-09-01 14:49 UTC, paulyuk approved these changes
Thanks a lot @amulyavarote 

These port changes look great.
I do wonder if we should have uniquely named ALL app-ids.  Let's try this and watch, just to make sure there's no collision.

LGTM

2022-09-01 14:49 UTC, paulyuk commented on .github/workflows/validate_new_quickstarts_pubsub.yaml
> +        quickstart_language: [go, csharp, javascript, python, java]
thank you !  see csharp!

2022-09-01 14:49 UTC, paulyuk commented on tutorials/pub-sub/README.md
> -  - "B: Message on B"
These lines are indeed brittle.

2022-09-01 14:49 UTC, merged