Fix readme service invocation description
dapr/quickstarts pull request #753
Opened 2022-11-23 22:50 UTC by bookinstock

2022-12-05 09:16 UTC, pravinpushkar approved these changes

2022-12-12 19:15 UTC, paulyuk requested changes
Hi.  I don't think I agree with this.  Even though this is a "direct HTTP call" and the http protocol is considered syncronous (unlike queue or message based), the client is still done async to be well behaved in web and cloud.

2022-12-12 22:37 UTC, yaron2 approved these changes

2023-01-11 07:58 UTC, paulyuk commented
Hi @bookinstock - I've reflected on this, spoken to others, and I'm flipping here.  This is an improvement and we'll take it.  Thank you for the contribution!

2023-01-11 07:58 UTC, paulyuk approved these changes

2023-01-11 07:59 UTC, merged