Made python quickstart README.md match the .NET purchasing example
dapr/quickstarts pull request #875
Opened 2023-06-06 22:32 UTC by nyemade-uversky

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PRs being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] The quickstart code compiles correctly
* [ ] You've tested new builds of the quickstart if you changed quickstart code
* [ ] You've updated the quickstart's README if necessary
* [ ] If you have changed the steps for a quickstart be sure that you have updated the automated validation accordingly. All of our quickstarts have annotations that allow them to be executed automatically as code. For more information see [mechanical-markdown](https://github.com/dapr/mechanical-markdown#readme). For user guide with examples see [Examples](https://github.com/dapr/mechanical-markdown/tree/main/examples#mechanical-markdown-by-example).

2023-06-06 22:45 UTC, greenie-msft approved these changes

2023-06-06 22:45 UTC, greenie-msft approved these changes
LGTM

2023-06-08 04:04 UTC, paulyuk requested changes
please see comments

2023-06-08 04:04 UTC, paulyuk commented on workflows/python/sdk/README.md
Thanks for teeing this up @nyemade-uversky 

Just need to fix line 35 to match cars left in stock.  That's python validation test fails. 
Before you PR pls try a `make validate` in the same folder as the makefile to check if tests will pass, and you'll catch lots of little errors.

2023-06-08 04:52 UTC, paulyuk commented on workflows/python/sdk/README.md
Also if easy could you please pull against the release-1.11 branch?

2023-06-16 15:07 UTC, merged