Fixups for JS crypto quickstart
dapr/quickstarts pull request #883
Opened 2023-06-13 16:43 UTC by ItalyPaleAle

2 fixes for JS crypto quickstart:

1. Fixed a typo in output
2. Added a "sleep" between writing the encrypted file and opening it for read, which hopefully reduces flakiness in the CI

2023-06-13 21:16 UTC, ItalyPaleAle commented
I believe the bug is actually in the JS SDK and this will fix it: https://github.com/dapr/js-sdk/pull/503

Will update this PR once a new SDK is released

2023-06-14 16:24 UTC, shubham1172 requested changes
Hi. could you please use SDK v3.1.2?

2023-06-14 16:33 UTC, ItalyPaleAle commented
@shubham1172 updated to use 3.1.2. I also switched to the `~3.1.2` syntax so it will install updates up to 3.2.0 (not included) automatically

2023-06-14 16:37 UTC, shubham1172 commented
> @shubham1172 updated to use 3.1.2. I also switched to the `~3.1.2` syntax so it will install updates up to 3.2.0 (not included) automatically

Thanks a lot, @ItalyPaleAle!

2023-06-15 06:18 UTC, paulyuk approved these changes
LGTM

2023-06-15 06:18 UTC, merged